### ISSUE TITLE
Usage of soon-to-be-deprecated DisplayBuffer internal APIs

### ISSUE THREAD

**Issue by as-cii** [ahuth/jasmine-runner#3]
We're going through a significant redesign of Atom's internals in atom/atom#11414, and we have noticed this package is using the `tokenizedLinesForScreenRows` API, which will be soon deleted from `TextEditor`.

In particular, it seems like that API is being used to access the line's indentation level, which you can compute also by calling `TextEditor.prototype.indentationForBufferRow`. Therefore, we recommend using it instead, so that this package won't break as soon as that pull-request gets merged.

Please, let me know if there's anything else I can do to assist you upgrading your package. Thanks!

**Comment by ahuth** [comment]
Thanks, @as-cii! I'll update this, and really appreciate the heads up

**Comment by ahuth** [comment]
Resolved by #5. Thanks again for the heads up!
